/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskDialog: typeof import('./components/AddTaskDialog.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    DecomposePreviewDialog: typeof import('./components/DecomposePreviewDialog.vue')['default']
    DeploymentPanel: typeof import('./components/DeploymentPanel.vue')['default']
    IntegrationTestEditor: typeof import('./components/IntegrationTestEditor.vue')['default']
    InteractiveClaudeTerminal: typeof import('./components/InteractiveClaudeTerminal.vue')['default']
    ModuleTaskTab: typeof import('./components/ModuleTaskTab.vue')['default']
    PlanPanel: typeof import('./components/PlanPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs/TabsTrigger.vue')['default']
    TaskEditCard: typeof import('./components/TaskEditCard.vue')['default']
    TaskStepEditor: typeof import('./components/TaskStepEditor.vue')['default']
    TddStepCards: typeof import('./components/TddStepCards.vue')['default']
    TestPanel: typeof import('./components/TestPanel.vue')['default']
    XtermComponent: typeof import('./components/XtermComponent.vue')['default']
  }
}
