package service

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"loafer-agent/internal/config"
)

// NginxManager 负责生成、写入、删除项目的 Nginx 站点配置，并触发 nginx 重载。
//
// 当 sshClient 不为 nil 时，所有文件操作和 nginx 重载通过 SSH 在远程服务器执行；
// 否则回退到本地执行（适用于后端直接部署在目标服务器上的场景）。
//
// 生成的配置为标准反向代理：前端静态文件由 deployDir/dist 提供，
// /api/ 与 /ws/ 反向代理到后端端口，并携带 WebSocket 升级头。
type NginxManager struct {
	cfg       *config.InfraConfig
	sshClient *SSHClient
}

// NewNginxManager 构造 Nginx 配置管理器。
// sshClient 为 nil 时使用本地文件系统操作。
func NewNginxManager(cfg *config.InfraConfig, sshClient *SSHClient) *NginxManager {
	return &NginxManager{cfg: cfg, sshClient: sshClient}
}

// nginxConfigTemplate Nginx 站点配置模板。
// 占位符顺序: projectName, projectID, upstreamName, backendPort,
// frontendPort, frontendDist, upstreamName(api), upstreamName(ws)
const nginxConfigTemplate = `# Nginx config for project %s (ID=%d)
# Generated by Loafer platform

upstream %s {
    server 127.0.0.1:%d;
}

server {
    listen %d;
    server_name _;

    # 前端静态产物根目录
    root %s;
    index index.html;

    # SPA history fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API 反向代理（含 WebSocket 升级支持）
    location /api/ {
        proxy_pass http://%s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }

    # WebSocket 专用端点
    location /ws/ {
        proxy_pass http://%s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
    }
}
`

// GenerateConfig 生成指定项目的 Nginx 站点配置文本。
//
// frontendPort 为 nginx 监听端口；backendPort 为后端服务端口；
// deployDir 为部署根目录，前端静态产物取自其下的 dist 子目录。
func (nm *NginxManager) GenerateConfig(projectID int64, projectName string, frontendPort, backendPort int, deployDir string) (string, error) {
	if frontendPort <= 0 || backendPort <= 0 {
		return "", fmt.Errorf("端口无效: frontend=%d backend=%d", frontendPort, backendPort)
	}
	if deployDir == "" {
		return "", fmt.Errorf("部署目录不能为空")
	}

	upstreamName := fmt.Sprintf("backend_%d", projectID)
	frontendDist := filepath.Join(deployDir, "dist")

	return fmt.Sprintf(nginxConfigTemplate,
		projectName,
		projectID,
		upstreamName,
		backendPort,
		frontendPort,
		frontendDist,
		upstreamName,
		upstreamName,
	), nil
}

// ConfigPath 返回指定项目的 Nginx 配置文件路径（基于 NginxConfigDir）。
func (nm *NginxManager) ConfigPath(projectID int64) string {
	dir := nm.cfg.NginxConfigDir
	if dir == "" {
		dir = "/etc/nginx/conf.d"
	}
	return filepath.Join(dir, fmt.Sprintf("loafer_%d.conf", projectID))
}

// WriteConfig 将配置内容写入指定路径。
// 当 SSH 客户端可用时写入远程服务器，否则写入本地文件系统。
func (nm *NginxManager) WriteConfig(configPath, content string) error {
	if configPath == "" {
		return fmt.Errorf("配置文件路径不能为空")
	}

	if nm.sshClient != nil {
		// 确保远程目录存在
		dir := filepath.Dir(configPath)
		if err := nm.sshClient.MkdirRemote(dir); err != nil {
			return fmt.Errorf("创建远程配置目录 %s 失败: %w", dir, err)
		}
		// 通过 SSH 写入远程文件
		return nm.sshClient.WriteRemoteFile(configPath, []byte(content), "644")
	}

	// 本地文件系统写入
	return nm.writeLocalFile(configPath, content)
}

// ReloadNginx 重载 Nginx 配置。
// 当 SSH 客户端可用时在远程服务器执行，否则在本地执行。
func (nm *NginxManager) ReloadNginx() error {
	binary := nm.cfg.NginxBinary
	if binary == "" {
		binary = "nginx"
	}

	if nm.sshClient != nil {
		// 先测试配置语法
		testCmd := fmt.Sprintf("%s -t 2>&1", binary)
		output, err := nm.sshClient.RunCommand(testCmd)
		if err != nil {
			return fmt.Errorf("nginx 配置语法检查失败: %w, output: %s", err, output)
		}

		// 重载配置
		reloadCmd := fmt.Sprintf("%s -s reload", binary)
		output, err = nm.sshClient.RunCommand(reloadCmd)
		if err != nil {
			return fmt.Errorf("重载 nginx 失败: %w, output: %s", err, output)
		}
		return nil
	}

	// 本地执行
	return nm.reloadLocalNginx(binary)
}

// RemoveConfig 删除指定 Nginx 配置文件，文件不存在时视为幂等成功。
func (nm *NginxManager) RemoveConfig(configPath string) error {
	if configPath == "" {
		return fmt.Errorf("配置文件路径不能为空")
	}

	if nm.sshClient != nil {
		return nm.sshClient.RemoveRemoteFile(configPath)
	}

	// 本地文件系统删除
	return nm.removeLocalFile(configPath)
}

// ---- 本地文件操作回退实现 ----

// writeLocalFile 将配置内容写入本地文件系统。
func (nm *NginxManager) writeLocalFile(configPath, content string) error {
	dir := filepath.Dir(configPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("创建配置目录 %s 失败: %w", dir, err)
		}
	}
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("写入 nginx 配置 %s 失败: %w", configPath, err)
	}
	return nil
}

// reloadLocalNginx 在本地执行 nginx -s reload。
func (nm *NginxManager) reloadLocalNginx(binary string) error {
	cmd := exec.Command(binary, "-s", "reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("重载 nginx 失败: %w, output: %s", err, string(output))
	}
	return nil
}

// removeLocalFile 删除本地配置文件，文件不存在时视为幂等成功。
func (nm *NginxManager) removeLocalFile(configPath string) error {
	if err := os.Remove(configPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("删除 nginx 配置 %s 失败: %w", configPath, err)
	}
	return nil
}
